<?php

namespace ContainerE5Al9jl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_Console_ValueResolver_Console_ArgumentResolver_ServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.debug.console.value_resolver.console.argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ValueResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/TraceableValueResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/ServiceValueResolver.php';

        return $container->privates['.debug.console.value_resolver.console.argument_resolver.service'] = new \Symfony\Component\Console\ArgumentResolver\ValueResolver\TraceableValueResolver(new \Symfony\Component\Console\ArgumentResolver\ValueResolver\ServiceValueResolver(($container->privates['.service_locator.dpiLQ5O'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], []))), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
