<?php

namespace ContainerE5Al9jl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Middleware_DecodeFailedMessageMiddlewareService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.middleware.decode_failed_message_middleware' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\DecodeFailedMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/DecodeFailedMessageMiddleware.php';

        return $container->privates['messenger.middleware.decode_failed_message_middleware'] = new \Symfony\Component\Messenger\Middleware\DecodeFailedMessageMiddleware(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'async' => ['privates', '.signing.messenger.default_serializer', 'get_Signing_Messenger_DefaultSerializerService', true],
            'failed' => ['privates', '.signing.messenger.default_serializer', 'get_Signing_Messenger_DefaultSerializerService', true],
        ], [
            'async' => '?',
            'failed' => '?',
        ]));
    }
}
