<?php

namespace ContainerDQpJ6be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Debug_Console_ValueResolver_Console_ArgumentResolver_DatetimeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.debug.console.value_resolver.console.argument_resolver.datetime' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\ValueResolver\TraceableValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ValueResolver/TraceableValueResolver.php';

        return $container->privates['.debug.console.value_resolver.console.argument_resolver.datetime'] = new \Symfony\Component\Console\ArgumentResolver\ValueResolver\TraceableValueResolver(($container->privates['console.argument_resolver.datetime'] ?? $container->load('getConsole_ArgumentResolver_DatetimeService')), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
