<?php

namespace ContainerDQpJ6be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_ArgumentResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.argument_resolver' shared service.
     *
     * @return \Symfony\Component\Console\ArgumentResolver\TraceableArgumentResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ArgumentResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/TraceableArgumentResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/ArgumentResolver/ArgumentResolver.php';

        return $container->services['console.argument_resolver'] = new \Symfony\Component\Console\ArgumentResolver\TraceableArgumentResolver(new \Symfony\Component\Console\ArgumentResolver\ArgumentResolver(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.debug.console.value_resolver.console.argument_resolver.backed_enum'] ?? $container->load('get_Debug_Console_ValueResolver_Console_ArgumentResolver_BackedEnumService'));
            yield 1 => ($container->privates['.debug.console.value_resolver.console.argument_resolver.uid'] ?? $container->load('get_Debug_Console_ValueResolver_Console_ArgumentResolver_UidService'));
            yield 2 => ($container->privates['.debug.console.value_resolver.console.argument_resolver.input_file'] ?? $container->load('get_Debug_Console_ValueResolver_Console_ArgumentResolver_InputFileService'));
            yield 3 => ($container->privates['.debug.console.value_resolver.console.argument_resolver.builtin_type'] ?? $container->load('get_Debug_Console_ValueResolver_Console_ArgumentResolver_BuiltinTypeService'));
            yield 4 => ($container->privates['.debug.console.value_resolver.console.argument_resolver.datetime'] ?? $container->load('get_Debug_Console_ValueResolver_Console_ArgumentResolver_DatetimeService'));
            yield 5 => ($container->privates['.debug.console.value_resolver.console.argument_resolver.map_input'] ?? $container->load('get_Debug_Console_ValueResolver_Console_ArgumentResolver_MapInputService'));
            yield 6 => ($container->privates['.debug.console.value_resolver.console.argument_resolver.service'] ?? $container->load('get_Debug_Console_ValueResolver_Console_ArgumentResolver_ServiceService'));
            yield 7 => ($container->privates['.debug.console.value_resolver.console.argument_resolver.default'] ?? $container->load('get_Debug_Console_ValueResolver_Console_ArgumentResolver_DefaultService'));
            yield 8 => ($container->privates['.debug.console.value_resolver.console.argument_resolver.variadic'] ?? $container->load('get_Debug_Console_ValueResolver_Console_ArgumentResolver_VariadicService'));
        }, 9), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BackedEnumValueResolver' => ['privates', '.debug.console.value_resolver.console.argument_resolver.backed_enum', 'get_Debug_Console_ValueResolver_Console_ArgumentResolver_BackedEnumService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\UidValueResolver' => ['privates', '.debug.console.value_resolver.console.argument_resolver.uid', 'get_Debug_Console_ValueResolver_Console_ArgumentResolver_UidService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\InputFileValueResolver' => ['privates', '.debug.console.value_resolver.console.argument_resolver.input_file', 'get_Debug_Console_ValueResolver_Console_ArgumentResolver_InputFileService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BuiltinTypeValueResolver' => ['privates', '.debug.console.value_resolver.console.argument_resolver.builtin_type', 'get_Debug_Console_ValueResolver_Console_ArgumentResolver_BuiltinTypeService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DateTimeValueResolver' => ['privates', '.debug.console.value_resolver.console.argument_resolver.datetime', 'get_Debug_Console_ValueResolver_Console_ArgumentResolver_DatetimeService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\MapInputValueResolver' => ['privates', '.debug.console.value_resolver.console.argument_resolver.map_input', 'get_Debug_Console_ValueResolver_Console_ArgumentResolver_MapInputService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\ServiceValueResolver' => ['privates', '.debug.console.value_resolver.console.argument_resolver.service', 'get_Debug_Console_ValueResolver_Console_ArgumentResolver_ServiceService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DefaultValueResolver' => ['privates', '.debug.console.value_resolver.console.argument_resolver.default', 'get_Debug_Console_ValueResolver_Console_ArgumentResolver_DefaultService', true],
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\VariadicValueResolver' => ['privates', '.debug.console.value_resolver.console.argument_resolver.variadic', 'get_Debug_Console_ValueResolver_Console_ArgumentResolver_VariadicService', true],
        ], [
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BackedEnumValueResolver' => '?',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\UidValueResolver' => '?',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\InputFileValueResolver' => '?',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\BuiltinTypeValueResolver' => '?',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DateTimeValueResolver' => '?',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\MapInputValueResolver' => '?',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\ServiceValueResolver' => '?',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\DefaultValueResolver' => '?',
            'Symfony\\Component\\Console\\ArgumentResolver\\ValueResolver\\VariadicValueResolver' => '?',
        ])), ($container->services['debug.stopwatch'] ??= new \Symfony\Component\Stopwatch\Stopwatch(true)));
    }
}
