<?php

namespace ContainerDQpJ6be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getController_IsSignatureValidAttributeListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'controller.is_signature_valid_attribute_listener' shared service.
     *
     * @return \Symfony\Component\HttpKernel\EventListener\IsSignatureValidAttributeListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/EventListener/IsSignatureValidAttributeListener.php';

        return $container->privates['controller.is_signature_valid_attribute_listener'] = new \Symfony\Component\HttpKernel\EventListener\IsSignatureValidAttributeListener(($container->privates['uri_signer'] ?? $container->load('getUriSignerService')));
    }
}
