<?php

namespace ContainerDQpJ6be;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwig_Runtime_EscaperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'twig.runtime.escaper' shared service.
     *
     * @return \Twig\Runtime\EscaperRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Extension/RuntimeExtensionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/twig/twig/src/Runtime/EscaperRuntime.php';

        return $container->privates['twig.runtime.escaper'] = new \Twig\Runtime\EscaperRuntime('UTF-8');
    }
}
