<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDQpJ6be\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDQpJ6be/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDQpJ6be.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDQpJ6be\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDQpJ6be\App_KernelDevDebugContainer([
    'container.build_hash' => 'DQpJ6be',
    'container.build_id' => '2ab76ad1',
    'container.build_time' => 1782312812,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDQpJ6be');
